### ISSUE TITLE
Population normalisation

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#192] opened 2023-11-13 12:36 UTC
In `normalised_pop_mass` the binary fraction is defined in the functions as `f_bin=0.7`.

However, in the population parameters an option is present to set the `binary_fraction`. This is not currently used to normalise the population mass.
The `normalised_pop_mass` should take the given binary fraction in the population parameters.

**Comment by mkruckow** [comment] 2024-07-17 08:18
Isn't this a duplicate of issue #168 ?

**Comment by astroJeff** [comment] 2024-08-22 14:51
Closing - this is a duplicate of #168

**Closed as completed by astroJeff** 2024-08-22 14:51 UTC
Labels: bug, enhancement, v2 feature
