### ISSUE TITLE
step_disrupted does not update stellar/CO state

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#345] opened 2024-06-27 20:17 UTC
The detached step does not check for the physical accuracy of its components:
`step_end` calls `update_star_states` to update the state of S1 to the correct type.
It looks like the step_disrupted does not update the stellar state

Expected behaviour: S1_state is updated when entering step_disrupted.

Potential solution: Force a update_star_states of CO_type, when entering the `disrupted/detached_step` or in `step_SN`.

| Binary Index | S1 State | S2 State | S1 Mass | S2 Mass | Event | State | Orbital Period |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 532 | H-rich_Core_H_burning | H-rich_Core_H_burning | 26.213338 | 24.474420 | ZAMS | detached | 579.504315 |
| 532 | stripped_He_Central_C_depletion | H-rich_Core_He_burning | 9.193318 | 13.938683 | CC1 | detached | 1381.985011 |
| 532 | BH | H-rich_Core_He_burning | 1.423424 | 13.938683 | NaN | disrupted | NaN |
| 532 | BH | stripped_He_Central_C_depletion | 1.423424 | 9.171099 | CC2 | disrupted | NaN |
| 532 | BH | NS | 1.423424 | 1.430361 | NaN | disrupted | NaN |
| 532 | NS | NS | 1.423424 | 1.430361 | END | disrupted | NaN |

**Comment by celiotine** [comment] 2024-09-09 18:04
@maxbriel do you have the full initial conditions of this binary for testing purposes? I will look into addressing this issue.
 Also, it looks like there may be a bigger classification issue here that we have discussed before (I think), so I assume this is meant to be an extra check/fix on top of a bigger fix? Ideally we wouldn't have 1.4Msun objects being labeled as BHs in the first place.

**Comment by maxbriel** [comment] 2024-09-13 12:40
@celiotine What additional info do you want? I believe the metallicity was at solar.

Looking at the original code, I believe that in step_end, `binary.update_star_states()` is called, which correctly sets the type. This is never done when entering the step_disrupted for the first time.

It probably has something to do with the interpolator, since this was from an IF population.
The IF interpolation is done using the CO_interpolation_class, while the state comes from the CO_type classifier.
See here: https://github.com/POSYDON-code/POSYDON/blob/251b3c6d895e0ef19169f2f34af968937c53b308/posydon/binary_evol/MESA/step_mesa.py#L965-L983


where `fv` is defined as the final_values output of the IF interpolator.

**Comment by celiotine** [comment] 2024-09-13 14:34
If you have the natal kick information, then I will be able to reproduce this exact binary. 
Thanks!

**Comment by maxbriel** [comment] 2024-09-13 16:23
I don't anymore, sorry!
But if you set the velocity to something very large to make it disrupt, you should be good to go :)

**Comment by celiotine** [comment] 2024-10-15 16:19
Not sure if this is related to Issue #413

**Comment by celiotine** [comment] 2024-10-17 14:43
resolved with PR #416

**Closed as completed by celiotine** 2024-10-17 14:43 UTC
Labels: bug, v2 feature, URGENT
